### ISSUE TITLE
作者能不能做个版本升级？

### ISSUE THREAD

**Issue by KingPengZero** [liangklfangl/react-universal-bucket#2]
"react": "^15.5.4",
    "react-addons-perf": "^15.4.2",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",
    "react-helmet": "^5.0.3",
    "react-redux": "^5.0.4",
    "react-router": "^3.0.2",

=》 
"react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-hot-loader": "next",
    "react-redux": "^5.0.6",
    "redux-async-connect": "^1.0.0-rc4",
    "react-router-dom": "^4.2.2",

**Comment by liangklfangl** [comment]
这个版本升级后可能会有问题，你可以试试，如果有问题欢迎讨论
